language: haxe

haxe:
  - "3.2.1"

install:
  # Install haxelibs
  - haxelib install hxcpp
  - haxelib install hxcs
  - haxelib install munit
  - haxelib install hamcrest
  - haxelib list
  
addons:
  apt:
    packages:
      - lynx
  
script:
  haxelib run munit test
