language: haxe

haxe:
  - "3.2.1"

install:
  # Install haxelibs
  - haxelib install hxcpp
  - haxelib install hxcs
  - haxelib install munit
  - haxelib install hamcrest
  - haxelib list
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  haxelib run munit test -kill-browser -browser firefox
